// DEPRECATED: This file is no longer used for sitemap generation
// The actual sitemap is now generated by app/routes/sitemap.xml.ts
// This file is kept for reference and potential future utility use

/**
 * NOTE: In React Router v7, sitemaps must be generated via resource routes.
 *
 * The active sitemap is at: /sitemap.xml (app/routes/sitemap.xml.ts)
 *
 * This file provides utility functions if you need to generate sitemap data
 * programmatically, but it is NOT automatically served at /sitemap.xml.
 *
 * For the working implementation, see: app/routes/sitemap.xml.ts
 */

import { source } from "./lib/source";

const SITE_URL = "https://docs.konnektr.com";

export async function getSitemap() {
  // Helper to build absolute URLs
  const url = (path: string) => `${SITE_URL}${path}`;

  // Get all docs pages from source
  const pages = await source.getPages();

  // Map each page to sitemap entry
  const items = await Promise.all(
    pages.map(async (page: any) => {
      // Exclude non-docs or special pages if needed
      if (page.data.type === "openapi") return undefined;
      const { lastModified } = await page.data.load();
      return {
        url: url(page.url),
        lastModified: lastModified ? new Date(lastModified) : undefined,
        changeFrequency: "weekly",
        priority: 0.5,
      };
    })
  );

  // Add static entries (homepage, docs root, etc.)
  const staticEntries = [
    {
      url: url("/"),
      changeFrequency: "monthly",
      priority: 1,
    },
    {
      url: url("/docs"),
      changeFrequency: "monthly",
      priority: 0.8,
    },
  ];

  // Return combined sitemap
  return [...staticEntries, ...items.filter(Boolean)];
}
